# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pulp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NupkgContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pulp_app.Content')),
                ('pkg_id', models.TextField()),
                ('version', models.TextField()),
                ('digest', models.TextField()),
                ('authors', models.TextField()),
            ],
            bases=('pulp_app.content',),
        ),
        migrations.CreateModel(
            name='NupkgImporter',
            fields=[
                ('importer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pulp_app.Importer')),
            ],
            options={
                'abstract': False,
            },
            bases=('pulp_app.importer',),
        ),
        migrations.CreateModel(
            name='NupkgPublisher',
            fields=[
                ('publisher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pulp_app.Publisher')),
            ],
            options={
                'abstract': False,
            },
            bases=('pulp_app.publisher',),
        ),
        migrations.AlterUniqueTogether(
            name='nupkgcontent',
            unique_together=set([('pkg_id', 'version', 'digest')]),
        ),
    ]
